# https://quay.github.io/clair/reference/config.html
introspection_addr: :8089
http_listen_addr: :8080
log_level: debug
#updaters:
#  sets:
#    - rhel
indexer:
  connstring: host=quay.example.com port=5432 dbname=clair user=clairuser password=clairpass sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  indexer_addr: localhost:8080
  connstring: host=quay.example.com port=5432 dbname=clair user=clairuser password=clairpass sslmode=disable
  max_conn_pool: 100
  run: ""
  migrations: true
#  updater_sets:
#  - "alpine"
#  - "aws"
#  - "debian"
#  - "oracle"
#  - "photon"
#  - "pyupio"
#  - "rhel"
#  - "suse"
#  - "ubuntu"
notifier:
  indexer_addr: localhost:8080
  matcher_addr: localhost:8080
  connstring: host=quay.example.com port=5432 dbname=clair user=clairuser password=clairpass sslmode=disable
  migrations: true
  disable_summary: false
  webhook: null
  amqp: null
  stomp: null
  delivery_interval: 1m
  poll_interval: 5m

# tracing and metrics
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent_endpoint: "localhost:6831"
    service_name: "clair"
metrics:
  name: "prometheus"
